### PR TITLE
[R-package] remove LazyData in DESCRIPTION

### PR DESCRIPTION
**Pull request by jameslamb**
I checked the `{uptasticsearch}` CRAN check results today, to see if the package was having any issues with R 4.1.0.

https://cran.r-project.org/web/checks/check_results_uptasticsearch.html

Looks like everything is fine, but there is one new NOTE:

```text
Version: 0.4.0
Check: LazyData
Result: NOTE
     'LazyData' is specified without a 'data' directory
Flavors: r-devel-linux-x86_64-debian-clang, r-devel-linux-x86_64-debian-gcc, r-devel-linux-x86_64-fedora-clang, r-devel-linux-x86_64-fedora-gcc, r-devel-windows-x86_64, r-devel-windows-x86_64-gcc10-UCRT, r-patched-linux-x86_64, r-patched-solaris-x86, r-release-linux-x86_64, r-release-windows-ix86+x86_64
```

This PR fixes it.

### CODE REVIEW

**Comment by jameslamb** [comment]
Not sure why CI wasn't triggered. I'm going to try closing and re-opening.

**Review by austin3dickey — APPROVED** [review]
Weird, CI still isn't working

**Comment by jameslamb** [comment]
> Weird, CI still isn't working

@alistaire47  is there some organization-level setting that paused GitHub Actions for this repo because of inactivity? It's been more than 6 months since our last commit, but CI did run as expected there:

* https://github.com/uptake/uptasticsearch/pull/217
* https://github.com/uptake/uptasticsearch/actions/runs/355088121

**Comment by alistaire47** [comment]
> @alistaire47 is there some organization-level setting that paused GitHub Actions for this repo because of inactivity?

Not AFAIK. Did a little digging and 

```yaml
on: [push]
```

might need to be 

```yaml
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
```
or similar?

**Comment by jameslamb** [comment]
nice @alistaire47 , that worked! 

I just pushed https://github.com/uptake/uptasticsearch/pull/219/commits/bf275fc4b319bac4d68add55742caf4c0cf747f7 and it seems like we have builds now!

**Comment by jameslamb** [comment]
I think the failing builds are just because we're using an old version of the `setup-miniconda` action. They seem to be succeeding on #220, so I'll merge that first and then we should be in business here.

**Comment by jameslamb** [comment]
thanks for the review @austin3dickey and for the help @alistaire47 !

**Pull request merged**
